//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalQuotation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuotationList()
        {
            this.QuotationDetails = new HashSet<QuotationDetail>();
        }
    
        public int Id { get; set; }
        public string Company { get; set; }
        public string Branch { get; set; }
        public string QuotationCategory { get; set; }
        public string Debitor { get; set; }
        public string CustomerName { get; set; }
        public string PhoneCode { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string CutCategory { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> IdType { get; set; }
        public string IdNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpirayDate { get; set; }
        public string AddressLine { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public Nullable<System.DateTime> QuotationExipryDate { get; set; }
        public Nullable<System.DateTime> RentalStartDate { get; set; }
        public Nullable<System.DateTime> RentalEndDate { get; set; }
        public Nullable<int> RentalDuration { get; set; }
        public Nullable<int> TotalRentalSum { get; set; }
        public Nullable<int> TotalAditionalCost { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> TotalNoOfVehicle { get; set; }
        public string QuotationStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetail> QuotationDetails { get; set; }
    }
}
