//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalQuotation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetail
    {
        public int Id { get; set; }
        public int QuotationId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Group { get; set; }
        public string CheckOutLocation { get; set; }
        public string CheckInLocation { get; set; }
        public Nullable<int> NoOfVehicle { get; set; }
        public Nullable<int> RentalSum { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> ParcelFuelAmount { get; set; }
        public Nullable<bool> Delivery { get; set; }
        public Nullable<bool> Collection { get; set; }
        public Nullable<bool> SCDW { get; set; }
        public Nullable<bool> WS { get; set; }
        public Nullable<bool> BabySeat { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> ADI { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual QuotationList QuotationList { get; set; }
    }
}
